AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  LambdalawnScraper
  SAM Template for LambdalawnScraper

Globals:
  Function:
    Timeout: 7

Resources:
  DeploymentPermission:
    Type: "AWS::Lambda::LayerVersionPermission"
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref ChromiumLayer
      Principal: '*'

  DeploymentPermission:
    Type: "AWS::Lambda::LayerVersionPermission"
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref PythonDepLayer
      Principal: '*'

  ChromiumLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: chromium-selenium-layer
      Description: Headless Chromium and Selenium WebDriver
      ContentUri: ./layers/selenium-binaries
      CompatibleRuntimes:
        - nodejs8.10
        - python3.8
        - python2.7
        - go1.x
        - java8
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain

  PythonDepLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: selenium-layer
      Description: Selenium, Requests, Chromedriver-binary
      ContentUri: ./layers/python-dependencies
      CompatibleRuntimes:
        - python3.7
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain

  LambdaLawnScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: LambdalawnScraper/
      FunctionName:
        LambdaLawnScraperFunction
      Handler: app.lambda_handler
      Runtime: python3.6
      MemorySize: 1280
      Timeout: 7
      Layers:
        - !Ref ChromiumLayer
        - !Ref PythonDepLayer
      Environment:
        Variables:
          CLEAR_TMP: "true"
          PATH: /var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin:/tmp/bin:/tmp/bin/lib

Outputs:
  LambdaLawnScraperFunction:
    Description: "Lawn Scraper Lambda Function ARN"
    Value: !GetAtt LambdaLawnScraperFunction.Arn