AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Lawn status parser
  SAM Template for parser

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  LambdaLawnParserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: LawnParser/
      FunctionName: LambdaLawnParserFunction
      Handler: app.lambda_handler
      Runtime: python3.6
      Policies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaENIManagementAccess
      MemorySize: 640
      Timeout: 5
      Role:
        Fn::ImportValue: LawnLambdaExecRole
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: lawnLambdaSecurityGroup
        SubnetIds:
          - Fn::ImportValue: lawnSubnetPrivateA
          - Fn::ImportValue: lawnSubnetPrivateB

Outputs:
  LambdaLawnParserFunction:
    Description: "ARN of lawn status parser lambda"
    Value: !GetAtt LambdaLawnParserFunction.Arn
