AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  3_basic_updater
  SAM Template for 3_basic_updater

Globals:
  Function:
    Timeout: 12

Resources:
  lawnBasicUpdater:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lawn_basic_updater/
      Environment:
        Variables:
          DB_HOST:
            Fn::ImportValue: lawnDB
      Handler: app.lambda_handler
      Runtime: python3.8
      MemorySize: 256
      Timeout: 7
      Policies:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaENIManagementAccess
      Role:
        Fn::ImportValue: LawnLambdaExecRole
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: lawnLambdaSecurityGroup
        SubnetIds:
          - Fn::ImportValue: lawnSubnetPrivateA
          - Fn::ImportValue: lawnSubnetPrivateB
      Events:
        S3UpdaterScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(2,32 * ? * * *)
            Description: Read from RDS and update site every 30mins
            Enabled: True

Outputs:
  lawnRDSwriter:
    Description: "Function that updates the static s3 site"
    Value: !GetAtt lawnBasicUpdater.Arn
