Description: >
  The network infrastructure under the BPL scraper app

Resources:
  lawnVPC: # VPC for this project, just for organization
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: !Join ["", [!Ref "AWS::StackName", "-VPC"]]

  lawnSubnetPublicA: # 1 of 2 public subnets
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1b
      CidrBlock: 10.0.0.0/24
      VpcId: !Ref lawnVPC
      Tags:
        - Key: Name
          Value: lawn-Subnet-Public-A

  lawnSubnetPublicB: # 2 of 2 public subnets
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1c
      CidrBlock: 10.0.1.0/24
      VpcId: !Ref lawnVPC
      Tags:
        - Key: Name
          Value: lawn-Subnet-Public-B

  lawnDBsubnetGroup: # RDS DB wants a subnet group. This is it
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: The two public subnets
      DBSubnetGroupName: lawn-DB-subnet-Group
      SubnetIds:
        - !Ref lawnSubnetPublicA
        - !Ref lawnSubnetPublicB

Outputs:
  lawnVPC:
    Description: A reference to the main app VPC
    Value: !Ref lawnVPC
    Export:
      Name: lawnVPC

  lawnDBsubnetGroup:
    Description: A reference to the public DB subnet group
    Value: !Ref lawnDBsubnetGroup
    Export:
      Name: lawnDBsubnetGroup
