Description: >
  Security group configs; what can access what in the VPC?

Resources:
  lawnDBgroup: # Security group for RDS
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Lawn DB SG
      VpcId:
        Fn::ImportValue: lawnVPC
      GroupName: lawn-DB-SG
      Tags:
        - Key: Name
          Value: lawn-DB-SG

  lawnDBGroupIngress: # DB can be written to from Lambdas group
    Type: "AWS::EC2::SecurityGroupIngress"
    Properties:
      GroupId: !Ref lawnDBgroup
      IpProtocol: -1
      SourceSecurityGroupId: !GetAtt lawnLambdaGroup.GroupId

  lawnDBGroupEgress: # DB can be read from Lambdas group
    Type: "AWS::EC2::SecurityGroupEgress"
    Properties:
      GroupId: !Ref lawnDBgroup
      IpProtocol: -1
      DestinationSecurityGroupId: !GetAtt lawnLambdaGroup.GroupId

  lawnLambdaGroup: # Security group for lambdas
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Lawn Lambdas r/w RDS access group
      VpcId:
        Fn::ImportValue: lawnVPC
      GroupName: lawn-Lambda-SG
      Tags:
        - Key: Name
          Value: lawn-Lambda-SG

  lawnLambdaRDSIngress: # Lambdas accepts SQL traffic from RDS
    Type: "AWS::EC2::SecurityGroupIngress"
    Properties:
      GroupId: !Ref lawnLambdaGroup
      IpProtocol: tcp
      FromPort: 6543
      ToPort: 6543
      SourceSecurityGroupId: !GetAtt lawnDBgroup.GroupId

  lawnLambdaRDSEgress: # Lambdas make RDS queries
    Type: "AWS::EC2::SecurityGroupEgress"
    Properties:
      GroupId: !Ref lawnLambdaGroup
      IpProtocol: -1
      DestinationSecurityGroupId: !GetAtt lawnDBgroup.GroupId

  lawnLambdaWebEgress: # Lambdas make web requests
    Type: "AWS::EC2::SecurityGroupEgress"
    Properties:
      GroupId: !Ref lawnLambdaGroup
      IpProtocol: -1
      CidrIp: 0.0.0.0/0

  lawnLambdaWebReturnsIngress: # Lambdas accept returning web responses
    Type: "AWS::EC2::SecurityGroupIngress"
    Properties:
      GroupId: !Ref lawnLambdaGroup
      IpProtocol: tcp
      FromPort: 1024
      ToPort: 65535
      CidrIp: 0.0.0.0/0

Outputs:
  lawnDBgroup:
    Description: VPC security group for RDS DB
    Value: !Ref lawnDBgroup
    Export:
      Name: lawnDBgroup

  lawnLambdaGroup:
    Description: VPC security group for Lambda functions
    Value: !Ref lawnLambdaGroup
    Export:
      Name: lawnLambdaGroup
