Description: >
  RDS SQL DB cfg; contains scraped lawn open/closed data

Resources:
  lawnDB: # Central DB. Use sidecar stack policy to avoid overwrites
    Type: AWS::RDS::DBInstance
    Properties: 
      AllocatedStorage: 100
      AllowMajorVersionUpgrade: False
      AutoMinorVersionUpgrade: False
      AvailabilityZone: us-east-1d
      DBInstanceClass: db.t2.micro
      StorageType: gp2 # aka SSD general purpose
      DBInstanceIdentifier: lawnDB
      DBSubnetGroupName: 
        Fn::ImportValue: lawnDBsubnetGroup
      MasterUsername: lawn_admin # Not public-facing, not worried
      MasterUserPassword: lawn_password # Not a secret
      PubliclyAccessible: False
      Port: 5432 # Default postgresql port
      Engine: postgres
      VPCSecurityGroups:
        - Fn::ImportValue: 
            lawnVpcSgPrivate # Doesn't touch the internet
           
Outputs:
  lawnDB:
    Description: A reference to the main app RDS DB
    Value: !Ref lawnDB
    Export:
      Name: lawnDB