AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  2_rds_writer
  SAM Template for 2_rds_writer

Globals:
  Function:
    Timeout: 12

Resources:
  lawnRDSwriter:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lawn_rds_writer/
      Environment:
        Variables:
          DB_HOST:
            Fn::ImportValue: lawnDB
      Handler: app.lambda_handler
      Runtime: python3.8
      MemorySize: 256
      Timeout: 12
      Policies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaENIManagementAccess
      Role:
        Fn::ImportValue: LawnLambdaExecRole
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: lawnLambdaSecurityGroup
        SubnetIds:
          - Fn::ImportValue: lawnSubnetPrivateA
          - Fn::ImportValue: lawnSubnetPrivateB
      Events:
        RDSWriteScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(1,31 * ? * * *)
            Description: Scrape web and write to RDS every 30mins
            Enabled: True

Outputs:
  lawnRDSwriter:
    Description: "Function that writes lawn status to rds rows"
    Value: !GetAtt lawnRDSwriter.Arn
